# Generated by Django 5.2.13 on 2026-04-29 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('narration', models.TextField()),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=14)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('upload_batch', models.CharField(blank=True, db_index=True, max_length=64)),
                ('hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Regex pattern to match narration/description', max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are checked first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category Rule',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='InternalLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=14)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('upload_batch', models.CharField(blank=True, db_index=True, max_length=64)),
                ('hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Internal Ledger Entry',
                'verbose_name_plural': 'Internal Ledger Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(choices=[('bank', 'Bank'), ('internal', 'Internal')], max_length=10)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6)),
                ('narration', models.TextField()),
                ('reconciliation_status', models.CharField(choices=[('matched', 'Matched'), ('probable', 'Probable'), ('unmatched', 'Unmatched')], db_index=True, max_length=10)),
                ('confidence_score', models.FloatField(default=0)),
                ('anomaly_flag', models.BooleanField(db_index=True, default=False)),
                ('anomaly_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.banktransaction')),
                ('internal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.internalledgerentry')),
                ('matched_with', models.ForeignKey(blank=True, help_text='Linked entry from the other source', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.ledger')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_match', models.BooleanField(default=False)),
                ('date_diff', models.IntegerField(default=0, help_text='Absolute difference in days')),
                ('narration_similarity', models.FloatField(default=0, help_text='0-100 fuzzy score')),
                ('overall_confidence', models.FloatField(default=0, help_text='0-100 weighted confidence')),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('probable', 'Probable Match'), ('unmatched_bank', 'Unmatched (Bank)'), ('unmatched_internal', 'Unmatched (Internal)')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_results', to='finance.banktransaction')),
                ('internal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_results', to='finance.internalledgerentry')),
            ],
            options={
                'verbose_name': 'Reconciliation Result',
                'ordering': ['-overall_confidence'],
            },
        ),
    ]
